### ISSUE TITLE
Running wkhtmltopdf on a Raspberry Pi with Ubuntu 16.04

### ISSUE THREAD

**Issue by bottlehall** [vapor-community/wkhtmltopdf#3]
It's been a bit of an ordeal, but I've now got a vapor project generating PDFs working on a Raspberry Pi running Ubuntu 16.04, but it needs an X11 server.

Ideally, I want wkhtmltopdf to run without the need for X11 to be running on the pi. Having installed the current latest version (0.12.3) via apt-get, I see that this version DOES need X11. So, I've tried compiling 0.12.4 from source and it succeeds, but still reports that I have not got the version of Qt patched for wkhtmltopdf, so still needs X11. I can't find out how to patch Qt in order to produce the version I want.

Any suggestions to get it working gratefully received!

**Comment by bygri** [comment]
Are you in a position to change from `wkhtmltopdf` to [WeasyPrint](http://weasyprint.org)? I've been using the latter myself (though not on Raspberry Pi) and even found the output better than `wkhtmltopdf`.

**Comment by bottlehall** [comment]
Hi

Thanks for the suggestion, unfortunately only one of the dependencies is easily available on Ubuntu on the Raspberry Pi.

Best wishes

Nick

**Comment by bottlehall** [comment]
Ignore that! I must have been doing something wrong!

I’ll have another go.

N

**Comment by bygri** [comment]
I made the suggestion after finding (admittedly old) [this reddit thread](https://www.reddit.com/r/raspberry_pi/comments/2xk13h/) which said "Weasyprint and PySerial works perfectly".

**Comment by bottlehall** [comment]
Dear Toby

Thank you! I’d managed to disable most of the repo whilst trying to figure something else out.

It’s all installed and running and  doesn’t need X11, so I can run the vapor server headlessly.

Should be fairly straightforward to write the views out to file and then point these to weasyprint.

Thanks again

Nick

**Comment by bygri** [comment]
No need to actually write to files with Weasy, either. It can use stdin/stdout. Here's the entirety of my current PDF generation code using Vapor's `Bytes` as returned from a view renderer.

```swift
import Core
import Foundation

func generateWeasy(html: Bytes) -> Bytes {
  // Fetch a PDF from WeasyPrint and return it
  let weasy = Process()
  let input = Pipe()
  let output = Pipe()
  let htmlData = Data(html)
  weasy.standardInput = input
  weasy.standardOutput = output
  weasy.launchPath = "/usr/local/bin/weasyprint"
  weasy.arguments = ["-f", "pdf", "-", "-"]
  weasy.launch()
  input.fileHandleForWriting.write(htmlData)
  input.fileHandleForWriting.closeFile()
  return output.fileHandleForReading.readDataToEndOfFile().makeBytes()
}
```

**Comment by bottlehall** [comment]
Thank you again, this is great. I’ll be able to drop it in very simply.

Nick
